version: "3.1"

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: qr-ieee-dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /docker/db/qr-code-ieee-pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
